---
- name: check_url_response
  uri:
   url: "{{item}}"    
   status: 200 
  with_items:
         - http://172.31.44.7
         - http://172.31.39.195
         - http://172.31.34.5
...            
 
